#!/usr/bin/env bash

#
# Runs at the end of git flow hotfix finish
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
VERSION=$1
ORIGIN=$2
BRANCH=$3

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

$SCRIPT_PATH/filter-flow-hotfix-finish-tag-message

# Implement your script here.
for key in gitflow.branch.develop gitflow.branch.master; do
  base_branch=$(git config --list | grep $key | cut -d '=' -f 2)
  git checkout $base_branch
  $SCRIPT_PATH/modules/pull-newest-branch.sh $key
  git push --force-with-lease
done

git push --tags
