#!/usr/bin/env bash

#
# Runs at the end of git flow hotfix delete
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
VERSION=$1

# Implement your script here.
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$current_branch" = "hotfix/$VERSION" ]];then
  base_branch=$(git config --list | grep gitflow.branch.master | cut -d '=' -f 2)
  git checkout $base_branch
fi
git branch -D hotfix/$VERSION
