#!/usr/bin/env bash

#
# Runs at the end of git flow feature delete
#
# Positional arguments:
# $1    The name of feature
#
# The following variables are available as they are exported by git-flow:
#
#
NAME=$1

# Implement your script here.
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$current_branch" = "feature/$NAME" ]];then
  base_branch=$(git config --list | grep gitflow.branch.develop)
  git checkout $base_branch
fi
git branch -D feature/$NAME
exit 0
