#!/usr/bin/env bash

# Runs at the end of git flow release finish
# generate change between two tag into a markdown table with commit, author, date and title
second_to_last_tag_commit=$(git show-ref --tags | tail -n 2 | head -n 1 | awk '{print $1}')
last_tag_commit=$(git show-ref --tags | tail -n 1  | awk '{print $1}')
last_tag=$(git show-ref --tags | tail -n 1 | awk '{print $2}' | cut -d / -f 3)

echo "# RELEASE $last_tag" > CHANGELOG.tmp.md
echo "| commit | commit author name | commit date | title |" >> CHANGELOG.tmp.md
echo "| ---- | ---- | ---- | ---- |" >> CHANGELOG.tmp.md

git --no-pager log --decorate=short --pretty=format:"| %h | %cn | %cs | %s |" $second_to_last_tag_commit..$last_tag_commit >> CHANGELOG.tmp.md

if [[ -f CHANGELOG.md ]]; then
  cat CHANGELOG.md >> CHANGELOG.tmp.md
fi
mv CHANGELOG.tmp.md CHANGELOG.md