#!/usr/bin/env bash
set -e

VERSION=$1

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_PATH/modules/functions.sh"

author_name=$(git config --list | grep user.name | tail -n 1 | cut -d "=" -f 2)
if [[ "$ADMIN_USERS" =~ "$author_name" ]]; then
  branch_name=hotfix/$VERSION
  if [[ "${branch_name}" != "${CURRENT_BRANCH}" ]]; then
    echo "fetch your ${branch_name} with: git fetch origin $branch_name:$branch_name"
    exit 1
  fi
  git config pull.rebase true
  git pull
  exit 0
fi

echo "you can't finish in local mode"
exit 1
