#!/usr/bin/env bash
set -e

VERSION=$1

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

${SCRIPT_PATH}/modules/pull-newest-branch.sh gitflow.branch.master

$SCRIPT_PATH/filter-flow-hotfix-finish-message

git push origin hotfix/$VERSION -f
