#!/usr/bin/env bash
set -e

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

$SCRIPT_PATH/filter-flow-release-finish-message
$SCRIPT_PATH/filter-flow-release-finish-tag-message

git add .
git commit --amend --no-edit

echo "disable finish in local mode"
exit 1
