#!/usr/bin/env bash

#
# Runs before git flow feature start
#

# Implement your script here.

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
${SCRIPT_PATH}/modules/pull-newest-branch.sh gitflow.branch.develop

exit 0
